- name: Download helm archive
  get_url:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-{{ helm.version }}-linux-amd64.tar.gz"
    checksum: "{{ helm.checksum }}"
    dest: "{{ helm.tmpDir }}"
  tags:
    - helm

- name: Create helm directory
  file:
    path: "{{ helm.tmpDir }}/helm-{{ helm.version }}"
    state: directory
    mode: 0755
  tags:
    - helm

- name: Unarchive helm
  unarchive:
    src: "{{ helm.tmpDir }}/helm-{{ helm.version }}-linux-amd64.tar.gz"
    dest: "{{ helm.tmpDir }}/helm-{{ helm.version }}"
  tags:
    - helm

- name: Copy helm binary to destination directory
  copy:
    src: "{{ helm.tmpDir }}/helm-{{ helm.version }}/linux-amd64/helm"
    dest: "{{ helm.binDir }}/helm"
    mode: 0755
  tags:
    - helm