- name: Set python interpreter if using Azure DevOps
  set_fact:
    ansible_python_interpreter: "{{ adoAnsiblePythonInterpreter }}"
  when: adoAnsiblePythonInterpreter is defined
  tags:
    - common

- name: Set playbook facts
  set_fact:
    resourceGroupName: "rg-{{ environmentShort }}-{{ locationShort }}-{{ commonName }}"
  tags:
    - common

- name: AKS List Cluster User Credential
  azure_rm_resource:
    resource_group: "{{ resourceGroupName }}"
    provider: ContainerService
    resource_type: managedClusters
    resource_name: "aks-{{ environmentShort }}-{{ locationShort }}-{{ commonName }}/listClusterUserCredential"
    api_version: "2018-03-31"
    method: POST
  register: clusterUserCredential
  changed_when: false
  tags:
    - common

- name: Run playbook
  block:
  - name: Fetch k8s configuration
    copy:
      content: "{{ clusterUserCredential.response.kubeconfigs[0].value | b64decode }}"
      dest: "{{ configuration.k8sconfiguration.dest }}"
    changed_when: false
    tags:
      - common

  - name: Include k8s.yml
    include_tasks: k8s/k8s.yml
    tags:
      - k8s

  - name: Include kubectl.yml
    include_tasks: kubectl.yml
    tags:
      - kubectl

  - name: Include helm.yml
    include_tasks: helm.yml
    tags:
      - helm

  - name: Include istioOperator.yml
    include_tasks: istioOperator.yml
    tags:
      - istioOperator
  
  - name: Include acr.yml
    include_tasks: acr.yml
    tags:
      - acr

  - name: Include externalDns.yml
    include_tasks: externalDns.yml
    tags:
      - externalDns

  - name: Include certManager.yml
    include_tasks: certManager.yml
    tags:
      - certManager

  - name: Include citrixCpx.yml
    include_tasks: citrixCpx.yml
    when: configuration.citrixCpx.enabled
    tags:
      - citrixCpx

  - name: Include goldpinger.yml
    include_tasks: goldpinger.yml
    tags:
      - goldpinger

  - name: Include velero.yml
    include_tasks: velero.yml
    tags:
      - velero

  - name: Include kubedb.yml
    include_tasks: kubedb.yml
    when: configuration.kubedb.enabled
    tags:
      - kubedb
  
  - name: Include datadog.yml
    include_tasks: datadog.yml
    when: configuration.datadog.enabled
    tags:
      - datadog

  - name: Include dnsTxtRecords.yml
    include_tasks: dnsTxtRecords.yml
    when: configuration.dnsTxtRecords.enabled
    tags:
      - dnsTxtRecords

  - name: Remove k8s configuration
    file:
      state: absent
      path: "{{ configuration.k8sconfiguration.dest }}"
    changed_when: false
    tags:
      - common

  rescue:
  - name: Remove k8s configuration
    file:
      state: absent
      path: "{{ configuration.k8sconfiguration.dest }}"
    changed_when: false
    tags:
      - common

  - name: Fail task
    fail:
      msg: "Rescue was invoked, task failed."
    tags:
      - common