configuration:
  k8sconfiguration:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/k8s-admin.conf
  istioOperator:
    operatorGitRepo: https://github.com/banzaicloud/istio-operator.git
    operatorBranch: 0.1.11
    namespace: istio-system
    istioVersion: 1.1.5
    gatewayHosts:
      - "*.{{ externalDnsZone }}"
  externalDns:
    namespace: external-dns
    labels:
      istio-injection: disabled
  dnsTxtRecords:
    enabled: false
    dmarc: "v=DMARC1; p=reject;"
    spf: "v=spf1 -all"
  certManager:
    namespace: cert-manager
    labels:
      istio-injection: disabled
  citrixCpx:
    enabled: false
    cpxVersion: "13.0-36.28"
    cicVersion: "1.1.3"
    namespace: citrix-cpx
    labels:
      istio-injection: disabled
  goldpinger:
    repository: quay.io/simongottschlag/goldpinger
    containerVersion: 1.3.0
    namespace: goldpinger
    labels:
      istio-injection: disabled
  velero:
    namespace: heptio-ark
    containerVersion: latest
    volumeSnapshotApiTimeout: 120
    resourceGroupName: "rg-{{ environmentShort }}-{{ locationShort }}-{{ commonName }}"
    storageAccountName: "strg{{ environmentShort }}{{ locationShort }}{{ commonName }}"
    labels:
      istio-injection: disabled
  kubedb:
    enabled: false
    namespace: kubedb
    state: present
    version: 0.11.0
    labels:
      istio-injection: disabled
  datadog:
    enabled: true
    state: present
    namespace: datadog
    site: datadoghq.eu
    labels:
      istio-injection: disabled
  clusterRoles:
  -
    name: istioNetworkAdmin
    state: present
    apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs: ["*"]
  defaultNamespaces:
  -
    name: kube-system
    labels:
      istio-injection: disabled
  -
    name: kube-public
    labels:
      istio-injection: disabled
  -
    name: default
    labels:
      istio-injection: enabled
  namespaces:
  -
    name: project-dev
    state: present
    labels:
      istio-injection: enabled
  -
    name: project-qa
    state: present
    labels:
      istio-injection: enabled
  -
    name: project-prd
    state: present
    labels:
      istio-injection: enabled

kubectl:
  version: "1.12.1"
  checksum: "sha512:f8a6f010ee769740d4271792187ee2ec38db385cd8ef86c1acb8858b3bc1393352ccaad82e97383ce43426ac372e705ce1466a47ad5ac6adfc037de0469ec133"
  bin_directory: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"
  tmp_directory: "{{lookup('env', 'TMPDIR') | default('/tmp',true)}}"
  owner: "root"
  group: "root"
  os: "linux"
  arch: "amd64"

helm:
  version: v2.12.0
  checksum: "sha512:7587b568e368314d44ea72e58d5304331bfe540dd9eb61580057068c413aab47f22a7f47d0cd1394fff2b308e18796359f460e8e19b205226f09f9caca0d671b"
  tmpDir: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"
  binDir: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"