configuration:
  k8sconfiguration:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/k8s-admin.conf
  istioOperator:
    enabled: true
    operatorGitRepo: https://github.com/banzaicloud/istio-operator.git
    operatorBranch: 0.2.3
    namespace: istio-system
    istioVersion: 1.2.4
    gatewayHosts:
      - "*.{{ externalDnsZone }}"
  externalDns:
    namespace: external-dns
    labels:
      istio-injection: disabled
  dnsTxtRecords:
    enabled: false
    dmarc: "v=DMARC1; p=reject;"
    spf: "v=spf1 -all"
  certManager:
    enabled: true
    state: present
    namespace: cert-manager
    helmRepo: https://charts.jetstack.io
    helmRepoName: jetstack
    helmChartName: cert-manager
    helmChartVersion: 0.11.0
    crdUrl: https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml
    crdChecksum: "sha512:30d4a3bf2f958e81aabe51f3616eb91212ac7b9f684ef1da41cff863247ab19132096ed099675ed31976ec3fff2197faa865d0b13f7dc5c1ad1c7579b42afef4"
    labels:
      istio-injection: disabled
  citrixCpx:
    enabled: false
    cpxVersion: "13.0-36.29"
    cicVersion: "1.2.0"
    namespace: citrix-cpx
    labels:
      istio-injection: disabled
  goldpinger:
    enabled: true
    repository: bloomberg/goldpinger
    containerVersion: 2.0.0
    namespace: goldpinger
    labels:
      istio-injection: disabled
  velero:
    enabled: true
    state: present
    namespace: velero
    helmChartName: velero
    helmChartVersion: 2.2.0
    azureStorageAccountName: "strg{{ environmentShort }}{{ locationShort }}{{ commonName }}"
    azureStorageAccountContainerName: velero
    azureResourceGroupName: "rg-{{ environmentShort }}-{{ locationShort }}-{{ commonName }}"
    labels:
      istio-injection: disabled
  kubedb:
    enabled: false
    namespace: kubedb
    state: present
    version: 0.11.0
    labels:
      istio-injection: disabled
  datadog:
    enabled: true
    state: present
    namespace: datadog
    site: datadoghq.eu
    labels:
      istio-injection: disabled
  clusterRoles:
  -
    name: istioNetworkAdmin
    state: present
    apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs: ["*"]
  defaultNamespaces:
  -
    name: kube-system
    labels:
      istio-injection: disabled
  -
    name: kube-public
    labels:
      istio-injection: disabled
  -
    name: default
    labels:
      istio-injection: enabled
  namespaces:
  -
    name: project-dev
    state: present
    labels:
      istio-injection: enabled
  -
    name: project-qa
    state: present
    labels:
      istio-injection: enabled
  -
    name: project-prd
    state: present
    labels:
      istio-injection: enabled

kubectl:
  version: "1.16.2"
  checksum: "sha512:69bb92c9b16c0286d7401d87cc73b85c88d6f9a17d2cf1748060e44525194b5be860daf7554c4c6319a546c9ff10f2b4df42a27e32d8f95a4052993b17ef57c0"
  bin_directory: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"
  tmp_directory: "{{lookup('env', 'TMPDIR') | default('/tmp',true)}}"
  owner: "root"
  group: "root"
  os: "linux"
  arch: "amd64"

helm:
  version: v2.16.0
  checksum: "sha512:c4fc75186e46bf3ce2e067f82140ae965a20504ad0df941742ecd64481ba4a1a02a9ebead9e837c642262ffd10d761d97a1a3b9d470868c7f09936c7bdff7924"
  tmpDir: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"
  binDir: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"