configuration:
  k8sconfiguration:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/k8s-admin.conf
  istioOperator:
    operatorGitRepo: https://github.com/banzaicloud/istio-operator.git
    operatorBranch: 0.1.11
    namespace: istio-system
    istioVersion: 1.1.5
    gatewayHosts:
      - "*.{{ externalDnsZone }}"
  externalDns:
    namespace: external-dns
    labels:
      istio-injection: disabled
  dnsTxtRecords:
    enabled: false
    dmarc: "v=DMARC1; p=reject;"
    spf: "v=spf1 -all"
  certManager:
    namespace: cert-manager
    labels:
      istio-injection: disabled
  citrixCpx:
    enabled: false
    cpxVersion: "13.0-36.28"
    cicVersion: "1.1.3"
    namespace: citrix-cpx
    labels:
      istio-injection: disabled
  goldpinger:
    repository: quay.io/simongottschlag/goldpinger
    containerVersion: 1.3.0
    namespace: goldpinger
    labels:
      istio-injection: disabled
  velero:
    namespace: heptio-ark
    containerVersion: latest
    volumeSnapshotApiTimeout: 120
    resourceGroupName: "rg-{{ environmentShort }}-{{ locationShort }}-{{ commonName }}"
    storageAccountName: "strg{{ environmentShort }}{{ locationShort }}{{ commonName }}"
    labels:
      istio-injection: disabled
  kubedb:
    enabled: false
    namespace: kubedb
    state: present
    version: 0.11.0
    labels:
      istio-injection: disabled
  datadog:
    enabled: true
    state: present
    namespace: datadog
    site: datadoghq.eu
    labels:
      istio-injection: disabled
  clusterRoles:
  -
    name: istioNetworkAdmin
    state: present
    apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs: ["*"]
  defaultNamespaces:
  -
    name: kube-system
    labels:
      istio-injection: disabled
  -
    name: kube-public
    labels:
      istio-injection: disabled
  -
    name: default
    labels:
      istio-injection: enabled
  namespaces:
  -
    name: project-dev
    state: present
    labels:
      istio-injection: enabled
  -
    name: project-qa
    state: present
    labels:
      istio-injection: enabled
  -
    name: project-prd
    state: present
    labels:
      istio-injection: enabled

kubectl:
  version: "1.15.0"
  checksum: "sha512:0906a8f7de1e5c5efd124385fdee376893733f343d3e8113e4f0f02dfae6a1f5b12dca3e2384700ea75ec39985b7c91832a3aeb8fa4f13ffd736c56a86f23594"
  bin_directory: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"
  tmp_directory: "{{lookup('env', 'TMPDIR') | default('/tmp',true)}}"
  owner: "root"
  group: "root"
  os: "linux"
  arch: "amd64"

helm:
  version: v2.14.1
  checksum: "sha512:e9cde3cc0034b96ea17f1f965f62c0e2c722f72cbebcd502cec00d8c35bf64045965f2c06cff64230c935558ca04dbd8525351d551291246eecc5489e282b41a"
  tmpDir: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"
  binDir: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}"